fix: verify of path exists

diff --git a/.github/workflows/kamal.yml b/.github/workflows/kamal.yml
--- a/.github/workflows/kamal.yml
+++ b/.github/workflows/kamal.yml
@@ -26,9 +26,15 @@ jobs:
     - name: Substitute Registry_Server, Web_Server_IP and HOST_NAME values
       id: substitute-values
       run: |
-        sed -i "s|REGISTRY_SERVER|${{ secrets.REGISTRY_SERVER }}|g" config/deploy.prod.yml
-        sed -i "s|HOST_NAME|${{ secrets.HOST_NAME }}|g" config/deploy.prod.yml
-        sed -i "s|WEB_SERVER_IP|${{ secrets.WEB_SERVER_IP }}|g" config/deploy.prod.yml
+        # Check if the file exists before attempting to modify it
+        if [ -f "config/deploy.prod.yml" ]; then
+          sed -i "s|REGISTRY_SERVER|${{ secrets.REGISTRY_SERVER }}|g" config/deploy.prod.yml
+          sed -i "s|HOST_NAME|${{ secrets.HOST_NAME }}|g" config/deploy.prod.yml
+          sed -i "s|WEB_SERVER_IP|${{ secrets.WEB_SERVER_IP }}|g" config/deploy.prod.yml
+        else
+          echo "Error: config/deploy.prod.yml file not found"
+          exit 1
+        fi
 
 
     - name: Checkout code
